typography_spectrum: 0.1290323
color:
  brandColors:
    - '#101010'
    - '#d7dee6'
    - '#afa6a1'
    - '#2a3a54'
    - '#0e6e92'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: porcupinex
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: ABOUT ME
    id: 5e173e52-d81c-4f50-9135-4ad4cd49dc9e
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Jørgen Larsen '
description: porcupinex
purpose: []
