typography_spectrum: 0.14022762118838727
color:
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  brandStrength: 0.39273544680327177
  lightness: 0.02088130870833993
  saturation: 0.46670428453944623
  rhythmicContrast: 0.42758279317058623
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.19922820175997913
analytics:
  google: null
  facebook: null
  twitter: null
name: porcupinex
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: ABOUT ME
    id: 5e173e52-d81c-4f50-9135-4ad4cd49dc9e
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Jørgen Larsen '
description: porcupinex
purpose: []
