name: porcupinex
favicon: null
layout_spectrum: 1
typography_spectrum: 0.44270351342856884
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b090c'
    - '#757678'
    - '#c1bdba'
    - '#ece7e3'
    - '#2c2b29'
  brandStrength: 0.17084904829971492
  lightness: 0.32017267495393753
  saturation: 0.5302162969019264
  rhythmicContrast: 0.817691175499931
purpose: []
