title: Jørgen Larsen (PORCUPINEX)
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.5
  rhythmicContrast: 0.75
  brandColors:
    - '#101010'
    - '#d7dee6'
    - '#afa6a1'
    - '#2a3a54'
    - '#0e6e92'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
name: porcupinex
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1290323
layout_spectrum: 0.8136201
