name: porcupinex
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60631
title: Jørgen Larsen (PORCUPINEX)
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101010'
    - '#d7dee6'
    - '#afa6a1'
    - '#2a3a54'
    - '#0e6e92'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 1
purpose: []
