typography_spectrum: 0.8475378390867263
color:
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  brandStrength: 0.1738128922879696
  lightness: 0.0791521412320435
  saturation: 0.07434345060028136
  rhythmicContrast: 0.38677734043449163
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5635418267920613
analytics:
  google: null
  facebook: null
  twitter: null
name: porcupinex
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: ABOUT ME
    id: 5e173e52-d81c-4f50-9135-4ad4cd49dc9e
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Jørgen Larsen '
description: PORCUPINEX
purpose: []
